name: downstream

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  html5gum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: untitaker/html5gum
      - run: rm -rf tests/html5lib-tests/
      - uses: actions/checkout@v2
        with:
          path: tests/html5lib-tests/
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test
