name: downstream

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
