name: downstream

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  parse5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: inikulin/parse5
          submodules: recursive
      - run: rm -rf test/data/html5lib-tests/
      - uses: actions/checkout@v2
        with:
          path: test/data/html5lib-tests/
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run unit-tests

  html5gum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: untitaker/html5gum
      - run: rm -rf tests/html5lib-tests/
      - uses: actions/checkout@v2
        with:
          path: tests/html5lib-tests/
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test

  nokogiri:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sparklemotion/nokogiri-test:mri-3.2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sparklemotion/nokogiri
          path: nokogiri
      - uses: actions/checkout@v3
        with:
          path: nokogiri/test/html5lib-tests
      - working-directory: nokogiri
        name: "Run the Nokogiri test suite"
        run: |
          bundle install
          bundle exec rake compile -- --enable-system-libraries
          bundle exec rake test
