name: downstream

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  nokogiri:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sparklemotion/nokogiri-test:mri-3.2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sparklemotion/nokogiri
          path: nokogiri
      - uses: actions/checkout@v3
        with:
          path: nokogiri/test/html5lib-tests
      - working-directory: nokogiri
        name: "Run the Nokogiri test suite"
        run: |
          bundle install
          bundle exec rake compile -- --enable-system-libraries
          bundle exec rake test
